@baseUrl = http://localhost:3000
### Requisição POST para criar um produto
POST {{baseUrl}}/products
Content-Type: application/json

### Requisição GET para se buscar um produto pelo nome
@product_name = algumaCoisa
GET {{baseUrl}}/products/{{product_name}}
Accept: application/json

HTTP/1.1 200  - OK
server: Werkzeug/3.1.3 Python/3.11.9
date: Sat, 22 Mar 2025 00:37:05 GMT
content-type: application/json
content-length: 39
connection: close