@port_url= http://localhost:3000
@product_name = produto_teste5
###
POST {{port_url}}/products
Content-Type: application/json

{
  "name": "{{product_name}}",
  "price": 5.99,
  "quantity": 1
}

HTTP/1.1 201  - CREATED
server: Werkzeug/3.1.3 Python/3.11.9
date: Sat, 22 Mar 2025 12:28:10 GMT
content-type: application/json
content-length: 86
connection: close
###
GET {{port_url}}/products/{{product_name}}
Accept: application/json
accept: */*

HTTP/1.1 200  - OK
server: Werkzeug/3.1.3 Python/3.11.9
date: Sat, 22 Mar 2025 12:28:16 GMT
content-type: application/json
content-length: 133
connection: close